### ISSUE TITLE
/auth username:token not working

### ISSUE THREAD

**Issue by gaboesquivel** [ghaiklor/telegram-bot-github#114]
Hi I was trying to set this up, but it seems that the `/auth` isn't working for some reason.

![](https://content.screencast.com/users/gaboesquivel5029/folders/Jing/media/1f7a287c-2eca-466c-9735-4c55a4cf8ca6/00000015.png)

**Comment by ghaiklor** [comment]
Hi

Somehow, it triggers `help` command instead of `auth`. Honestly, I don't have any ideas why this happened. Can you try to trigger other commands to check out. In case, any of commands will trigger `help` command, then it some issue with telegram?

**Comment by ghaiklor** [comment]
@gaboesquivel just checked my own profile and it works. Can you provide more details?

**Comment by ghaiklor** [comment]
Closing, due working auth command
