### ISSUE TITLE
Notifications batching

### ISSUE THREAD

**Issue by l4l** [ghaiklor/telegram-bot-github#131]
Is there a feature that notify you at most once a hour/couple of hours/day/etc?

It would be nice to have one, e.g if you answer pr review it might be very annoying to have a message every few minutes.

**Comment by ghaiklor** [comment]
It uses `If-Modified-Since` header which is supported by GitHub API. It will notify you only if GitHub notifications were updated since your last notification in github.

see https://github.com/ghaiklor/telegram-bot-github/blob/dev/src/services/GitHubNotifications.js#L38

**Comment by ghaiklor** [comment]
Should be fixed with #139
