### ISSUE TITLE
Me blocked user?

### ISSUE THREAD

**Issue by CliffS** [ghaiklor/telegram-bot-github#133]
I'm getting the following output from the bot, whatever command I use:

```
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"YOU_BLOCKED_USER"}
```

**Comment by ghaiklor** [comment]
@CliffS I have no idea, maybe you blocked the bot ?

**Comment by CliffS** [comment]
Very odd.  It was showing as blocked, even though I have no recollection of using it before, let alone blocking it.

Sorry for wasting your time.

**Comment by rajiearee** [comment]
i got the same problem
