### ISSUE TITLE
Desktop Theme Editor - surface selecting pipette

### ISSUE THREAD

**Issue by BlackRedDead** [ghaiklor/telegram-bot-github#145]
I got send here by [GʀᴀᴩʜɪᴄL 🅛🅐🅝🅖🅔🅛🅘🅔🅡](t.me/XxCryptonightxX) to post my Idea here:
A Pipette Tool to select areas to edit in the Theme Editor.
### Steps to operate:
1. Select Pipette Tool.
2. Point and click the Area where the Surface or Text is or would appear you want to edit.
3. Get a list in the Editor with all the Entrys (of the Surfaces/Texts) of the selected Area to edit.

Idk if that is possible via Bot, would just be nice to see that someday as it would simplify creating Theme's a lot!

Thx for your time.
Greetz
BRD

**Comment by ghaiklor** [comment]
@BlackRedDead are you sure that you are in the right repository ? 😺

**Comment by BlackRedDead** [comment]
nope, but evidence suggested that the answer is "clearly not!" :D
