### ISSUE TITLE
Telegram Desktop Mac OS: No longer able to click on comment/pull requests as links 

### ISSUE THREAD

**Issue by mmoayyed** [ghaiklor/telegram-bot-github#80]
I am running Telegram Desktop on Mac OS; `v2.92.91486`. I was just informed that this is the brand new version of the client running on Swift if that matters at all.

Problem is, when I receive Github notifications from a repo I am no longer able to click on the title of the notification to open up the browser and get to the post.

Example:

```
New comment on cas#2498 OAuth2 Authentication broken - created access tokens already expired
```

Mousing over the part `cas#2498 OAuth2 Authentication broken - created access tokens already expired` turns the mouse cursor into a hand, indicating that one might be able to click on that title and get to the relevant Github issue, but no matter how many times I click, the browser is never opened to browse to Github and that issue. 

I don't know if this is something that needs to be fixed on the Telegram side perhaps. If so, please LMK and I'll move the issue over.

Thank you very much for this great bot!

**Comment by ghaiklor** [comment]
@mmoayyed IMO, that's on Telegram's side. I just sending a link to your contact, without any Telegram-specific features.

**Comment by mmoayyed** [comment]
Great. Thanks for the update. I'll report this to them.

**Comment by mmoayyed** [comment]
One additional question: Should I report this issue here https://github.com/telegramdesktop/tdesktop ?

Because when I look at their releases, I don't see mine is listed there at all and it sounds like that might be a different project. My Telegram Desktop client was downloaded and installed via the App Store.

I understand this has nothing to do with you or the project, but was wondering if you'd know the answer :) 

Thanks again.

**Comment by ghaiklor** [comment]
@mmoayyed really, IDK where it should be reported :)
